### ISSUE TITLE
Cancelling area selection shows an error in notifications

### ISSUE THREAD

**Issue by rednir** [OttoAllmendinger/gnome-shell-screenshot#181]
When clicking "select area" with the gnome-screenshot backend, then pressing esc to cancel it, an error will be shown.
![image](https://user-images.githubusercontent.com/10225220/150089528-88f4eb5f-50ca-454c-9c46-6ecbf59b1dd4.png)
on GNOME 41.3

**Comment by OttoAllmendinger** [comment]
should be fixed now

>

**Comment by jsjunior** [comment]
Hi.
Still occurs in Gnome 42.5 with version 68.

**Comment by Commenter25** [comment]
Still an issue on Gnome 43 on version 69, showing the same error. It looks like there was an commit attempting to throw an error saying selection aborted, but I don't think this should throw an error at all.
